language: python

python:
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "AfURFb/ZW2k6fjLbWMFKX88m9eeGFvVbT99elqU8jJWYTq1KrRUAax1WN3IBOFPS1kc9mfDLAzL9T9I2Mnl9t8qnfBpVb+4g6u7BkdHI4OobDPpO/GvOJvnuT5fMkwvvFIPJ1wp2fuj0c4JjWSNSdEo4yxSz93qK78+HhrH+17RfDaK3/Xq6dr6o0nQQIV8wDq6+4n4lnEPxU5X4UbKi2L8LXbOKZtzCRBDBN94i/js5Jhc8ErjTtdmlBsxI7j3xpDRwe+tN49qFETRZ/K61Soo4Cf5h3sDg0PmJrHJBBcoW01xd51XD5/yUhlkThxLsYixQCcjIonM0XeQMA0VfQhj35ViNer5vUdmUsL8PrUD1DN1gxFBhOUBnjp0wdKe8NtSEQEMbi0o+/5JZ6d+v73wwk/wIRvPufydY3sgCNQ1TPQT8A73Z4fOnnF0QiWziR1IiK0MblYZi7D+K6ExhLvxiomVvTiZe1u1nosSDpva7+5VwUUQjqFHx3EsPdcRhWXF0gW2BuSqCVwrI96R8JuHWSVYKkT3npT2y432Fj9CSJUVOz5pOCa+APm/tJikVop+9ParEel0N+TdcKvcMTBFw4ILoz4tdoYqfoOaPfOHmsD8JPxF5hiXLDUGjYXAw/ltxjTYqFcy8X/3kzH0JL/kGIPYvcWwj7PBK6NZt8j4="

script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
